import styles from '../../styles/Home.module.css'
import Footer from './Footer'
import NavBar from './NavBar'
import Head from 'next/head'

const Layout = ( {children} ) => {

    console.log(children);

    return (
        <>
            <Head>
                <title>Coding With A Purpose</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/CWAP.png" />
            </Head>
            <main>
                <NavBar/>
                    {children}
                <Footer/>
            </main>
        </>
    );
}

export default Layout;