import '../styles/globals.css'
import { ParallaxProvider } from 'react-scroll-parallax'
import Layout from '../comps/Layout/Layout'
import { PAGES_MANIFEST } from 'next/dist/shared/lib/constants'
import Head from 'next/head'

const MyApp = ({ Component, pageProps }) => {

  const getLayout = Component.getLayout ||
   ((page) => (<Layout>{page}</Layout>))

  return getLayout(
    <>
      <Head>
        <title>Coding With A Purpose</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/CWAP.png" />
      </Head>
      <main>
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
