import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Displaybox from '../comps/Display/Displaybox'
import Logo from '../comps/Display/Logo'
import Description from '../comps/Display/Description'
import Footer from '../comps/Layout/Footer'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import { ParallaxProvider } from 'react-scroll-parallax'
import { useState} from 'react'
import NavBar from '../comps/Layout/NavBar'
import ParallaxLayout from '../comps/Layout/ParallaxLayout'
import { motion } from 'framer-motion'
import AboutUs from '../comps/Display/AboutUs'
import { AiOutlinePhone, AiFillCode, AiOutlineLike, AiFillFileText } from 'react-icons/ai'
import Mission from '../comps/Display/Mission'

const grid = [
  {
    title: "About",
    href: "/About",
    image: AiOutlineLike,
    description: "What is our Mission?"
  },
  {
    title: "Contact Us",
    href: "/ContactUs",
    image: AiOutlinePhone,
    description: "Any Questions?"
  },
  {
    title: "Projects",
    href: "/Projects",
    image: AiFillCode,
    description: "Cool stuff we do"
  },
  {
    title: "Blog",
    href: "/Blog",
    image: AiFillFileText,
    description: "Interesting articles"
  }
]

const Home = () => {

  const [selected, setSelected] = useState(null);

  return (
    <>
      <Head>
        <title>Coding With A Purpose</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Parallax pages={3} className={styles.parallax}>
          <ParallaxLayer factor={1} className={styles.top} style={{backgroundColor:'var(--black)', backgroundSize: 'cover'}}>
            <NavBar Motion={true}/>
          </ParallaxLayer>
          <ParallaxLayer factor={0.5} offset={0.1} speed={0.5}>
            <Description>
              Coding With A Purpose
            </Description>
          </ParallaxLayer>
          <ParallaxLayer offset={1} speed={0.5} style={{backgroundColor:'var(--black)', backgroundSize: 'cover'}}>
            <Mission/>
          </ParallaxLayer>
          <ParallaxLayer offset={2} speed={0.5}>
            <AboutUs/>
          </ParallaxLayer>
        </Parallax>     
      </main>
    </>
  )
}


Home.getLayout = function getLayout(page) {
  return (
    <ParallaxProvider motion>
        {page}
    </ParallaxProvider>
  )
}

export default Home;
