import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Displaybox from '../comps/Display/Displaybox'
import Logo from '../comps/Display/Logo'
import Description from '../comps/Display/Description'
import Footer from '../comps/Layout/Footer'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import { ParallaxProvider } from 'react-scroll-parallax'
import { useState} from 'react'
import ParallaxLayout from '../comps/Layout/ParallaxLayout'

const inter = Inter({ subsets: ['latin'] })

const grid = [
  {
    title: "About",
    href: "/About",
    image: "/tech.jpg",
    description: "What is our Mission?"
  },
  {
    title: "Contact Us",
    href: "/ContactUs",
    image: "/contactus.jpg",
    description: "Any Questions?"
  },
  {
    title: "Projects",
    href: "/Projects",
    image: "/codecode.jpg",
    description: "Cool stuff we do"
  },
  {
    title: "Blog",
    href: "/Blog",
    image: "/blog.jpg",
    description: "Interesting articles"
  }
]

const Home = () => {

  const [selected, setSelected] = useState(null);

  return (
    <>
      <Head>
        <title>Coding With A Purpose</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Parallax pages={2} className={styles.parallax}>
          <ParallaxLayer factor={1} className={styles.top} style={{backgroundImage:'url(/background4.avif)', backgroundSize: 'cover'}}/>
          <ParallaxLayer factor={0.5} offset={0.1} speed={0.5}>
            <Logo width={320} height={320} className={styles.biglogo}/>
            <Description/>
          </ParallaxLayer>
          <ParallaxLayer offset={1} speed={0.5}>
            <h1 className={styles.bottomdescription}>
              About Us...
            </h1>
            <div className={styles.grid}>
              
            {grid.map((el) => {

              if (!(selected == el.title))
                  return (
                  <Displaybox 
                      title={el.title} 
                      href={el.href} 
                      src={el.image}
                      key={el.title}
                      onMouseEnter={() => setSelected(el.title)}
                  >
                      {el?.description}
                  </Displaybox>
                  )
              else 
                  return(
                  <Displaybox 
                      title={el.title} 
                      href={el.href} 
                      src={el.image}
                      key={el.title}
                      onMouseLeave={() => setSelected(null)}
                      animate={{
                          scale: [1, 1.25, 1.25 , 1, 1],
                          borderRadius: ["20%", "20%", "50%", "50%", "20%"],
                      }}
                  >
                      {el?.description}
                  </Displaybox>
                  )
              })}
            </div>
            <Footer/>
          </ParallaxLayer>
        </Parallax>     
      </main>
    </>
  )
}


Home.getLayout = function getLayout(page) {
  return (
    <ParallaxProvider>
        {page}
    </ParallaxProvider>
  )
}

export default Home;
