import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Displaybox from '../comps/Display/Displaybox'
import Logo from '../comps/Display/Logo'
import Description from '../comps/Display/Description'
import styled from 'styled-components'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import { AiFillCode, AiOutlinePhone, AiOutlineSmile, AiTwotoneCrown } from 'react-icons/ai';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Coding With A Purpose</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Parallax pages={2} className={styles.parallax}>
          <ParallaxLayer factor={1} className={styles.top} style={{backgroundImage:'url(/background.jpg)', backgroundSize: 'cover'}}/>
          <ParallaxLayer factor={0.5} offset={0.1} speed={0.5}>
            <Logo/>
            <Description/>
          </ParallaxLayer>
          <ParallaxLayer offset={1} speed={0.5}>
            <h1 className={styles.bottomdescription}>
              About Us...
            </h1>
            <div className={styles.grid}>
                <Displaybox title="About" href="/About" src="/tech.jpg">What is our Mission?</Displaybox>
                <Displaybox title="Contact Us" href="/ContactUs" src="/contactus.jpg">Any Questions?</Displaybox>
                <Displaybox title="Projects" href="/Projects" src="/codecode.jpg">Cool stuff we do</Displaybox>
                <Displaybox title="Blog" href="/Blog" src="/blog.jpg">Interesting articles</Displaybox>
            </div>
          </ParallaxLayer>
        </Parallax>
        
      </main>
    </>
  )
}
